version: '3'

services:

    app:
        build:
            context: ./golang
            dockerfile: Dockerfile
            target: dev
        volumes:
            - ./app:/app
        depends_on:
            - mysql
            - rabbitmq
        working_dir: /app
        ports:
            - 8080:8080

    clickhouse-server:
        image: yandex/clickhouse-server
        container_name: clickhouse-server
        hostname: clickhouse-server
        ports:
            - 8123:8123
            - 9000:9000
        expose:
            - 9000
            - 9009
        volumes:
            - ./data:/var/lib/clickhouse
            - ./log/clickhouse-server/:/var/log/clickhouse-server/

    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15671:15671"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        depends_on:
            - mysql

    mysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        # command: --init-file /data/application/init.sql
        volumes:
            # - ./mysql/init.sql:/data/application/init.sql
            - ./mysql/lib/mysql:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: clickhouse_test
            MYSQL_USER: nameless
            MYSQL_PASSWORD: secret